// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace test.Models;

public partial class Choice
{
    [Key]
    [Column("ChoiceID")]
    public int ChoiceId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Value { get; set; }

    [InverseProperty("ModelAnsNavigation")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("StudentChoice")]
    public virtual ICollection<StudentExamAn> StudentExamen { get; set; } = new List<StudentExamAn>();

    [ForeignKey("ChoiceId")]
    [InverseProperty("Choices")]
    public virtual ICollection<Question> Qids { get; set; } = new List<Question>();
}