// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace test.Models;

[Table("Department", Schema = "HumanResources")]
public partial class Department
{
    [Key]
    [Column("DeptID")]
    public int DeptId { get; set; }

    [Required]
    [Column("Dept_Name")]
    [StringLength(50)]
    [Unicode(false)]
    public string DeptName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string DeptDesc { get; set; }

    [Column("MgrID")]
    public int? MgrId { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    [ForeignKey("MgrId")]
    [InverseProperty("Departments")]
    public virtual Instructor Mgr { get; set; }
}