// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace test.Models;

[Table("Exam")]
public partial class Exam
{
    [Key]
    [Column("ExamID")]
    public int ExamId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndTime { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Instructions { get; set; }

    [Column("CrsID")]
    public int? CrsId { get; set; }

    [ForeignKey("CrsId")]
    [InverseProperty("Exams")]
    public virtual Course Crs { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<StudentExamAn> StudentExamen { get; set; } = new List<StudentExamAn>();

    [ForeignKey("ExamId")]
    [InverseProperty("Exams")]
    public virtual ICollection<Question> Qids { get; set; } = new List<Question>();
}