// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace test.Models;

[Table("Instructor", Schema = "HumanResources")]
public partial class Instructor
{
    [Key]
    [Column("InsID")]
    public int InsId { get; set; }

    public float? Salary { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Position { get; set; }

    public bool? IsAdmin { get; set; }

    [Column("PersonID")]
    public int? PersonId { get; set; }

    [InverseProperty("Ins")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    [InverseProperty("Mgr")]
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    [ForeignKey("PersonId")]
    [InverseProperty("Instructors")]
    public virtual Person Person { get; set; }
}