// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace test.Models;

public partial class Question
{
    [Key]
    [Column("QID")]
    public int Qid { get; set; }

    [StringLength(6)]
    [Unicode(false)]
    public string Complexity { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Type { get; set; }

    public int Weight { get; set; }

    [Column("QText")]
    [StringLength(255)]
    [Unicode(false)]
    public string Qtext { get; set; }

    [Column("CrsID")]
    public int? CrsId { get; set; }

    public int? ModelAns { get; set; }

    [ForeignKey("CrsId")]
    [InverseProperty("Questions")]
    public virtual Course Crs { get; set; }

    [ForeignKey("ModelAns")]
    [InverseProperty("Questions")]
    public virtual Choice ModelAnsNavigation { get; set; }

    [InverseProperty("QidNavigation")]
    public virtual ICollection<StudentExamAn> StudentExamen { get; set; } = new List<StudentExamAn>();

    [ForeignKey("Qid")]
    [InverseProperty("Qids")]
    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();

    [ForeignKey("Qid")]
    [InverseProperty("Qids")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}