// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace test.Models;

[Table("Student")]
public partial class Student
{
    [Key]
    [Column("StID")]
    public int StId { get; set; }

    public float? FinalEvaluation { get; set; }

    [Column("PersonID")]
    public int? PersonId { get; set; }

    [ForeignKey("PersonId")]
    [InverseProperty("Students")]
    public virtual Person Person { get; set; }

    [InverseProperty("St")]
    public virtual ICollection<StudentCourse> StudentCourses { get; set; } = new List<StudentCourse>();

    [InverseProperty("St")]
    public virtual ICollection<StudentExamAn> StudentExamen { get; set; } = new List<StudentExamAn>();
}