// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace test.Models;

public partial class Topic
{
    [Key]
    [Column("TopicID")]
    public int TopicId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TopicName { get; set; }

    [Column("CrsID")]
    public int? CrsId { get; set; }

    [ForeignKey("CrsId")]
    [InverseProperty("Topics")]
    public virtual Course Crs { get; set; }
}