// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DAL.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DAL.Context
{
    public partial interface IExamSystemContextProcedures
    {
        Task<int> ChoicesInsertAsync(string value, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ExamInsertAsync(DateTime? StratTime, DateTime? EndTime, string Instructions, int? CrsID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<examQuestionWithAnswersResult>> examQuestionWithAnswersAsync(int? eId, int? stdId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> QuestionsInsertAsync(string Complexity, string Type, string QText, int? CrsID, int? ModelAns, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
