// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities;

public partial class Course
{
    [Key]
    public int CrsID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CrsName { get; set; }

    public int? InsID { get; set; }

    public int? DeptID { get; set; }

    [ForeignKey("DeptID")]
    [InverseProperty("Courses")]
    public virtual Department Dept { get; set; }

    [InverseProperty("Crs")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [ForeignKey("InsID")]
    [InverseProperty("Courses")]
    public virtual Instructor Ins { get; set; }

    [InverseProperty("Crs")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("Crs")]
    public virtual ICollection<StudentCourse> StudentCourses { get; set; } = new List<StudentCourse>();

    [InverseProperty("Crs")]
    public virtual ICollection<Topic> Topics { get; set; } = new List<Topic>();
}