// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities;

[Table("Department", Schema = "HumanResources")]
public partial class Department
{
    [Key]
    public int DeptID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Dept_Name { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string DeptDesc { get; set; }

    public int? MgrID { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    [ForeignKey("MgrID")]
    [InverseProperty("Departments")]
    public virtual Instructor Mgr { get; set; }
}