// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities;

[Table("Exam")]
public partial class Exam
{
    [Key]
    public int ExamID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndTime { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Instructions { get; set; }

    public int? CrsID { get; set; }

    [ForeignKey("CrsID")]
    [InverseProperty("Exams")]
    public virtual Course Crs { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    [InverseProperty("Exam")]
    public virtual ICollection<StudentExamAn> StudentExamen { get; set; } = new List<StudentExamAn>();
}