// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities;

[PrimaryKey("ExamID", "QID")]
public partial class ExamQuestion
{
    [Key]
    public int ExamID { get; set; }

    [Key]
    public int QID { get; set; }

    public int? StID { get; set; }

    [ForeignKey("ExamID")]
    [InverseProperty("ExamQuestions")]
    public virtual Exam Exam { get; set; }

    [ForeignKey("QID")]
    [InverseProperty("ExamQuestions")]
    public virtual Question QIDNavigation { get; set; }

    [ForeignKey("StID")]
    [InverseProperty("ExamQuestions")]
    public virtual Student St { get; set; }
}