// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Entities
{
    public partial class examQuestionWithAnswersResult
    {
        [Column("Full Name")]
        public string FullName { get; set; }
        public string QText { get; set; }
        [Column("Student Answer")]
        public string StudentAnswer { get; set; }
        [Column("Model Answer")]
        public string ModelAnswer { get; set; }
    }
}
