// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities;

[Table("Instructor", Schema = "HumanResources")]
public partial class Instructor
{
    [Key]
    public int InsID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Position { get; set; }

    public int? PersonID { get; set; }

    [InverseProperty("Ins")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    [InverseProperty("Mgr")]
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    [ForeignKey("PersonID")]
    [InverseProperty("Instructors")]
    public virtual Person Person { get; set; }
}