// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities;

public partial class Question
{
    [Key]
    public int QID { get; set; }

    [StringLength(6)]
    [Unicode(false)]
    public string Complexity { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Type { get; set; }

    public int Weight { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string QText { get; set; }

    public int? CrsID { get; set; }

    public int? ModelAns { get; set; }

    [ForeignKey("CrsID")]
    [InverseProperty("Questions")]
    public virtual Course Crs { get; set; }

    [InverseProperty("QIDNavigation")]
    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    [ForeignKey("ModelAns")]
    [InverseProperty("Questions")]
    public virtual Choice ModelAnsNavigation { get; set; }

    [InverseProperty("QIDNavigation")]
    public virtual ICollection<StudentExamAn> StudentExamen { get; set; } = new List<StudentExamAn>();

    [ForeignKey("QID")]
    [InverseProperty("QIDs")]
    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();
}