// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities;

[Table("Student")]
public partial class Student
{
    [Key]
    public int StID { get; set; }

    public float? FinalEvaluation { get; set; }

    public int? PersonID { get; set; }

    [InverseProperty("St")]
    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    [ForeignKey("PersonID")]
    [InverseProperty("Students")]
    public virtual Person Person { get; set; }

    [InverseProperty("St")]
    public virtual ICollection<StudentCourse> StudentCourses { get; set; } = new List<StudentCourse>();

    [InverseProperty("St")]
    public virtual ICollection<StudentExamAn> StudentExamen { get; set; } = new List<StudentExamAn>();
}