// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities;

[PrimaryKey("StID", "ExamID", "QID")]
public partial class StudentExamAn
{
    [Key]
    public int StID { get; set; }

    [Key]
    public int ExamID { get; set; }

    [Key]
    public int QID { get; set; }

    public int? StudentChoiceID { get; set; }

    public int? IsCorrect { get; set; }

    public int? RN { get; set; }

    [ForeignKey("ExamID")]
    [InverseProperty("StudentExamen")]
    public virtual Exam Exam { get; set; }

    [ForeignKey("QID")]
    [InverseProperty("StudentExamen")]
    public virtual Question QIDNavigation { get; set; }

    [ForeignKey("StID")]
    [InverseProperty("StudentExamen")]
    public virtual Student St { get; set; }

    [ForeignKey("StudentChoiceID")]
    [InverseProperty("StudentExamen")]
    public virtual Choice StudentChoice { get; set; }
}