// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities;

public partial class Topic
{
    [Key]
    public int TopicID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TopicName { get; set; }

    public int? CrsID { get; set; }

    [ForeignKey("CrsID")]
    [InverseProperty("Topics")]
    public virtual Course Crs { get; set; }
}